### ISSUE TITLE
How to treat mono repos or lerna repos?

### ISSUE THREAD

**Issue by BioPhoton** [ts-chore/deprecation-manager#83]
As more and more people work with mono repos, lerna setups or "multi package repos" we could have a thing on that.

Firat inputs:
- A single setup file or a file per package or both and extending form root?
  - ~~How to deal with groups?~~ separate config files
  - ~~How to get tags?~~ tagFormat option in the config file e. g. `crawler@${SEMVER_TOKEN}`
  - file changes in other libs?

**Comment by timdeschryver** [comment]
Good question.
I think the most simple solution would be to have separate configs in the root of each package?
I'm not sure how mono repos deal with tags tbh, won't all packages have the same tag version?

**Comment by BioPhoton** [comment]
Lerna  tags look like that `<package>@<semver>`

All formats i know are:
- `v<semver>`
- `version<semver>`
`<package>@<semver>`
